const repoCharacter =[
    {
      "id": "639b5c5702ed8737dccae2c3",
      "nomeDoJogador": "Breno",
      "nome": "PickBoyy",
      "raca": "Humano",
      "classe": "barbaro",
      "nivel": 1,
      "experiencia": 0,
      "forca": 12,
      "destreza": 12,
      "constituicao": 12,
      "inteligencia": 12,
      "sabedoria": 12,
      "carisma": 12,
    },
    {
      "id": "639b5c6202ed8737dccae2c6",
      "nomeDoJogador": "Gbriel",
      "nome": "Niendol",
      "raca": "Humano",
      "classe": "barbaro",
      "nivel": 1,
      "experiencia": 0,
      "forca": 12,
      "destreza": 12,
      "constituicao": 12,
      "inteligencia": 12,
      "sabedoria": 12,
      "carisma": 12,
    },
    {
      "id": "639b5c6c02ed8737dccae2c9",
      "nomeDoJogador": "Emilly",
      "nome": "Emy",
      "raca": "Humano",
      "classe": "barbaro",
      "nivel": 1,
      "experiencia": 0,
      "forca": 12,
      "destreza": 12,
      "constituicao": 12,
      "inteligencia": 12,
      "sabedoria": 12,
      "carisma": 12,
    },
  ] 


export default repoCharacter